title: "GitHub Portfolio"
description: "Computer Science Student & Aspiring Software Engineer"
remote_theme: pages-themes/cayman@v0.2.0

nav:
  - name: "Home"
    link: /
  - name: "About"
    link: /about/
  - name: "Projects"
    link: /projects/
